---
- name: pin defaults
  ansible.builtin.set_fact:
    openwrt_ssh: "{{ openwrt_ssh }}"
    openwrt_scp: "{{ openwrt_scp }}"
    openwrt_ssh_user: "{{ openwrt_ssh_user }}"
    openwrt_ssh_host: "{{ openwrt_ssh_host }}"
    openwrt_user_host: "{{ openwrt_ssh_user | quote }}@{{ openwrt_ssh_host | quote }}"
    ansible_ssh_transfer_method: "{{ openwrt_ssh_transfer_method }}"
    ansible_ssh_use_tty: "{{ openwrt_ssh_use_tty }}"
    ansible_scp_if_ssh: "{{ openwrt_scp_if_ssh }}"
    ansible_remote_tmp: "{{ openwrt_remote_tmp }}"
  when: "'openwrt' in group_names"
  tags: always

- name: retrieve /etc/os-release
  slurp:
    src: /etc/os-release
  register: os_release_slurp
  when: "'openwrt' in group_names"

- name: populate fact os_release
  ansible.builtin.set_fact:
    os_release: >-
      {{
        _os_release_dict.keys() | map('lower')
        | zip(_os_release_dict.values())
        | items2dict(key_name=0, value_name=1)
      }}
  vars:
    _os_release_lines: "{{ os_release_slurp['content'] | b64decode | split('\n') }}"
    _os_release_split: "{{ _os_release_lines | map('regex_search', '^([A-Z_0-9]+)=\"(.*)\"$', '\\1', '\\2') | reject('none') }}"
    _os_release_dict: "{{ dict(_os_release_split) }}"
  when: "'openwrt' in group_names"

- name: Check if internet connection is available
  command: ping -c 1 google.com
  register: openwrt_internet_connection
  changed_when: false
  when: "'openwrt' in group_names"

- name: Set internet connection available fact
  ansible.builtin.set_fact:
    openwrt_internet_connection_available: "{{ openwrt_internet_connection.rc == 0 }}"
  when: "'openwrt' in group_names"

- name: install recommended packages (apk)
  include_tasks: packages_apk.yml
  when:
    - "'openwrt' in group_names"
    - "openwrt_install_recommended_packages | bool"
    - "(os_release.version_id | default('snapshot')) == 'snapshot' or (os_release.version_id | default('0') is version('25.12', '>='))"

- name: install recommended packages (opkg)
  include_tasks: packages_opkg.yml
  when:
    - "'openwrt' in group_names"
    - "openwrt_install_recommended_packages | bool"
    - "(os_release.version_id | default('snapshot')) != 'snapshot' and (os_release.version_id | default('0') is version('25.12', '<'))"
