---
dependency:
  name: galaxy
  requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: openwrt_latest
    image: openwrt/rootfs:latest
    command: sleep infinity
    pre_build_image: true
    network_mode: host
    groups:
      - openwrt
  - name: openwrt_x86_64-23.05.3
    image: openwrt/rootfs:x86_64-23.05.3
    command: sleep infinity
    pre_build_image: true
    network_mode: host
    groups:
      - openwrt
  - name: openwrt_x86_64-22.03.2
    image: openwrt/rootfs:x86_64-22.03.2
    command: sleep infinity
    pre_build_image: true
    network_mode: host
    groups:
      - openwrt
  - name: openwrt_x86_64-21.02.5
    image: openwrt/rootfs:x86_64-21.02.5
    command: sleep infinity
    pre_build_image: true
    network_mode: host
    groups:
      - openwrt
  - name: openwrt_x86_64-19.07.10
    image: openwrt/rootfs:x86_64-19.07.10
    command: "sh -c 'while true; do sleep 10000; done'"
    pre_build_image: true
    network_mode: host
    groups:
      - openwrt
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
